[build]
  base    = ""
  publish = "build"
  command = "sh build.sh"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "sh build.sh"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = "sh build.sh"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = "sh build.sh"